spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/carritoCompra
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      data: classpath:/scripts/region.sql
---
spring:
   profiles: test
   datasource:
      url: jdbc:h2:./test
      username: root
      password:
      driverClassName: org.h2.Driver
      data: classpath:/scripts/data.sql
   jpa:
     database: h2
     hibernate:
       ddl-auto: create
     show-sql: true